# This file was automatically @generated by Smaug.
# Do not manually edit this file. Edit Smaug.toml instead.

require "smaug/draco/lib/draco.rb"
require "app/components/common/index.rb"
require "app/entities/common/index.rb"
require "app/systems/common/index.rb"
require "app/worlds/common/index.rb"
require "app/components/collector/index.rb"
require "app/systems/collector/index.rb"
require "smaug/draco-periodic/lib/draco/periodic.rb"
require "smaug/draco-state/lib/draco/state.rb"
require "smaug/draco-events/lib/draco/events.rb"

require "app/components/index.rb"
require "app/entities/index.rb"
require "app/systems/index.rb"
require "app/worlds/index.rb"
