name: flappy-coin-collector
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: ereborstudios/flappy-coin-collector
  name: flappy-coin-collector
  build_command: unzip -d dist builds/collector-example-html5.zip
  output_dir: dist/
